Launch Hardhat Tools and Testing module
base-org/web pull request #104
Opened 2023-11-02 18:40 UTC by briandoyle81CB

**What changed? Why?**
Reorganized files to launch the Hardhat Tools and Testing content under docs > Building on Base > Guides

Added Two new lessons to Basecamp under the Hardhat module (Contract to Contract Interaction, and Events)

Updated sidebar.js for the main instance and Basecamp to support above

Setup sidebars.

**Notes to reviewers**

**How has it been tested?**
Manually

2023-11-02 21:10 UTC, taycaldwell requested changes

2023-11-02 21:10 UTC, taycaldwell commented on apps/base-docs/docs/hardhat-tools-and-testing/hardhat-test-coverage/hardhat-test-coverage-sbs.md
Because a lot of this content is lifted from Base Camp and moved over into the Guides section, some of the wording doesn't make sense anymore.

For example, in this file, under the section `My first test coverage`, it states "In the Hardhat testing lesson, you explored how to test your smart contracts with Hardhat and Typechain". 

I don't think we can make assumptions like this for the reader anymore, as they likely are discovering the content on it's own outside of Base Camp.

2023-11-02 21:15 UTC, briandoyle81CB commented on apps/base-docs/docs/hardhat-tools-and-testing/hardhat-test-coverage/hardhat-test-coverage-sbs.md
Good catch, I'll do a pass

2023-11-03 16:59 UTC, taycaldwell approved these changes

2023-11-03 18:07 UTC, merged