chore: add beliefs.social to ecosystem page
base-org/web pull request #1110
Opened 2024-10-21 16:03 UTC by dalechyn

**What changed? Why?**

**Notes to reviewers**

**How has it been tested?**

2024-10-21 16:03 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-10-28 15:05 UTC, wbnns requested changes
@dalechyn 

Hello, looks like a bunch of artifacts got brought into this PR. Can you please remove them so it's just the files you meant to change?

2024-10-28 15:06 UTC, dalechyn commented
> @dalechyn 
> 
> 
> 
> Hello, looks like a bunch of artifacts got brought into this PR. Can you please remove them so it's just the files you meant to change?

Apologies, nvim linter linted the whole project.
Will do in the next 2 hrs.

2024-10-30 14:11 UTC, dalechyn commented
Seems like the master branch was force-pushed back when I've added this PR.

2024-11-02 06:37 UTC, wbnns requested changes
@dalechyn 

Thanks for this PR! Could you please change the category to defi and also confirm if this is on Base or on Degen L3?

2024-11-04 13:52 UTC, dalechyn commented
> @dalechyn
> 
> Thanks for this PR! Could you please change the category to defi and also confirm if this is on Base or on Degen L3?

Sure! Yes, this operates on base, you can check yourself at beliefs.social.

2024-11-04 13:52 UTC, dalechyn commented on apps/web/src/data/ecosystem.json
> +      "social"
```suggestion
      "defi"
```

2024-12-18 20:07 UTC, wbnns commented
@dalechyn

Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please fix the merge conflict and update the category + subcategory?

We'll do our best to review as soon as possible once you do! 🙏

2024-12-24 11:38 UTC, wbnns commented
@dalechyn 

Please also rebase to resolve the merge conflict.

2024-12-27 15:02 UTC, closed without merging

2024-12-27 15:02 UTC, wbnns commented
@dalechyn Please open a new PR, when you are ready, incorporating the above changes. 🙏