Fwx
base-org/web pull request #1161
Opened 2024-10-28 10:44 UTC by earth2378

**What changed? Why?**

**Notes to reviewers**

**How has it been tested?**

2024-10-28 10:44 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-02 07:12 UTC, wbnns requested changes
@earth2378 

Thanks for this PR! Left a couple of nits in-line. Could you also please confirm what markets are available on Base?

2024-11-02 07:12 UTC, wbnns commented on apps/web/src/data/ecosystem.json
> +  "imageUrl": "/images/partners/your-project-logo.png"
This should be a your logo name

2024-11-02 07:12 UTC, wbnns commented on apps/web/src/data/ecosystem.json
> +  "description": " FWX is a permissionless perps DEX, any token can be permissionlessly listed to create their own onchain perps and lending markets. Trades are hedged in onchain DEXs to create zero
Please remove extra space at beginning of description

2024-12-19 13:20 UTC, wbnns commented
Closing due to inactivity

2024-12-19 13:20 UTC, closed without merging