[Tutorial] Add Paymaster + Wagmi tutorial and remove large .gif for OCK theme tutorial
base-org/web pull request #1188
Opened 2024-11-01 19:19 UTC by hughescoin

**What changed? Why?**

- Add new tutorial for Paymaster integration for Wagmi apps
- Update links in OCK Fund tutorial
- Remove large .gif file from OCK Theme tutorial

**Notes to reviewers**

**How has it been tested?**
yes

2024-11-01 19:19 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-01 20:58 UTC, ericbrown99 commented on apps/base-docs/tutorials/docs/1_ock-swap-theme.md
> +In this tutorial, you'll learn how to create a swap component with a custom theme using OnchainKit. We'll start with the OnchainKit App Template and modify it to include a swap interface for ERC20 to
"on the Base" -> "on Base"

2024-11-01 20:59 UTC, ericbrown99 commented on apps/base-docs/tutorials/docs/1_ock-swap-theme.md
> +By the end of this tutorial, you should be able to:
"you should be" ->  "you will be"

2024-11-01 21:00 UTC, ericbrown99 commented on apps/base-docs/tutorials/docs/1_ock-swap-theme.md
> +This tutorial uses OnchainKit. Familiarity with its basic concepts will be helpful.
Link to OnchainKit for ease

2024-11-01 21:07 UTC, ericbrown99 reviewed
Noted a couple typos, otherwise looks good!

2024-11-02 04:53 UTC, wbnns requested changes
@hughescoin 

Heya, looks like this still brings in the large gif; can you please remove?

![2024-11-02 at 13 52 51@2x](https://github.com/user-attachments/assets/4bb84fa0-d25d-4486-a007-d606e851a87e)

2024-11-04 18:37 UTC, ericbrown99 approved these changes

2024-11-04 18:37 UTC, cb-heimdall commented
Review Error for ericbrown99 @ 2024-11-04 18:37:55 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

2024-11-05 23:11 UTC, closed without merging