update Alien Base logo and description
base-org/web pull request #1195
Opened 2024-11-04 12:42 UTC by darkalienlord

**What changed? Why?** Updating Logo and description of Alien Base on Base Ecosystem page

**Notes to reviewers**

**How has it been tested?**

2024-11-04 12:42 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-08 06:55 UTC, wbnns commented on apps/web/src/data/ecosystem.json
> +    "description": "Alien Base is building the Base trading hub for efficiently trading tokens and memecoins onchain. Offering aggregated liquidity, limit orders, yield farming and more, Alien techno
Please update:

`building the Base trading hub`

To:

`building a Base trading hub`

---

Additionally, please revise to drop the superlative, `to the fullest`

2024-11-08 06:55 UTC, wbnns requested changes
@darkalienlord 

Thanks for the update! Left a couple of small nits in-line.

2024-12-19 13:08 UTC, wbnns commented
@darkalienlord 

Since some time has passed without update, closing this PR for now. If you all would like to pursue this change in the future please open a new one. 🙏

2024-12-19 13:08 UTC, closed without merging