Typo Update hardhat-verify-sbs.md
base-org/web pull request #1244
Opened 2024-11-11 09:50 UTC by onasilos

**What changed? Why?**

There is a typo in the "Getting an Etherscan key" section — the image filename and link use "harhat-verify-create-key.png" instead of "hardhat-verify-create-key.png". Fixed.

<img width="622" alt="Снимок экрана 2024-11-11 в 12 49 19" src="https://github.com/user-attachments/assets/ae1a4f24-4017-412d-8df5-2b345a12cf13">

**Notes to reviewers**

**How has it been tested?**

2024-11-11 09:50 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-14 20:00 UTC, zencephalon approved these changes

2024-11-15 08:51 UTC, onasilos commented
[zencephalon](https://github.com/zencephalon) please merge it.

2024-12-05 11:00 UTC, wbnns approved these changes
ACK

@onasilos Thanks for contributing and for building on Base 🔵

2024-12-05 11:48 UTC, wbnns requested changes
@onasilos 

Apologies, in moving to merge this I see CI/CD is failing. Could you please update your branch and resolve?

2024-12-19 21:17 UTC, wbnns commented
@onasilos 

Hello, thanks for updating this. In subsequent review, this is actually a typo in the file name itself, not the link; this change will break the image. If you'd like to fix both, please feel free to open a new PR 🙏

2024-12-19 21:17 UTC, closed without merging