Adding Layerswap to the Base Ecosystem page
base-org/web pull request #1263
Opened 2024-11-18 17:22 UTC by annatantushyan19

2024-11-18 17:22 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-12-05 17:45 UTC, wbnns requested changes
@annatantushyan19 

Hi there! Thanks for this PR! Could you please update the landing page to point to one that is Base-focused with the network already selected, for folks that would be coming from base.org?

2024-12-10 16:27 UTC, annatantushyan19 commented
@wbnns 

Thanks for the feedback! Just updated!

2024-12-19 21:24 UTC, wbnns commented
@annatantushyan19 

Hi there! Thanks for the update! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please rebase + update your PR, conforming to the new format by removing the tag, and defining the category (infra) and subcategory (bridge)?

We'll do our best to review as soon as possible once you do! 🙏

2024-12-23 09:42 UTC, annatantushyan19 commented
@wbnns just updated! Let me know if it works!

2025-01-14 13:09 UTC, wbnns approved these changes
ACK

@annatantushyan19 Thanks for building on Base 🔵

2025-01-25 16:51 UTC, wbnns commented on apps/web/src/data/ecosystem.json
> +    "imageUrl": "/images/partners/Layerswap-logo.png"
There is a comma missing here which is causing the PR to fail

2025-01-25 16:51 UTC, wbnns commented
@annatantushyan19 Hello, it looks like there is a JSON formatting error in the code that needs to be fixed -- I marked it inline.

2025-01-27 16:39 UTC, annatantushyan19 commented
@wbnns updated!

2025-01-31 20:47 UTC, wbnns approved these changes

2025-01-31 20:56 UTC, merged