Add Portuguese 🇵🇹🇧🇷 - “Base é para todos”
base-org/web pull request #1288
Opened 2024-11-23 04:03 UTC by supermari0x

**What changed? Why?**
Adding the Portuguese version of “Base is for everyone”: “Base é para todos” LFB! 💙

**Notes to reviewers**

**How has it been tested?**
Ran yarn workspace @app/web dev
Navigated to http://localhost:3000 in my browser
Slider is working as expected

2024-11-23 04:03 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-12-06 10:13 UTC, wbnns commented
@supermari0x 

Bom dia, Mario! Could you please resolve the merge conflict?

2024-12-19 21:35 UTC, wbnns requested changes
@supermari0x 

Requested an additional change in-line 🙏

2024-12-19 21:35 UTC, wbnns commented on apps/web/src/components/base-org/root/SlidingTextSection/index.tsx
> +  const text = ' Base is for everyone - بایس للجمیع - Base es para todos - 基地适合所有人 - La Base è per tutti - Base est pour tout le monde - Base ni ya kila mtu - Base yɛ ma obiara - Base nye amesiame tɔ
There should be a space at the end of the line after `-` and before `'`

2025-01-14 12:26 UTC, wbnns commented on apps/web/src/components/base-org/root/SlidingTextSection/index.tsx
> +  const text = ' Base is for everyone - بایس للجمیع - Base es para todos - 基地适合所有人 - La Base è per tutti - Base est pour tout le monde - Base ni ya kila mtu - Base yɛ ma obiara - Base nye amesiame tɔ
There should be a space after `-` and before `'` at the end of the line

2025-01-14 12:26 UTC, wbnns commented
@supermari0x Left an additional request for change in-line and there is also a merge conflict 🙏

2025-01-14 12:35 UTC, supermari0x commented on apps/web/src/components/base-org/root/SlidingTextSection/index.tsx
> +  const text = ' Base is for everyone - بایس للجمیع - Base es para todos - 基地适合所有人 - La Base è per tutti - Base est pour tout le monde - Base ni ya kila mtu - Base yɛ ma obiara - Base nye amesiame tɔ
Done ✅

2025-01-14 12:35 UTC, supermari0x commented
@wbnns fixed ✅

2025-02-05 00:31 UTC, wbnns commented
Adding in #1702

2025-02-05 00:31 UTC, closed without merging