swap '_mint' for 'transfer'
base-org/web pull request #129
Opened 2023-11-15 03:16 UTC by SilviaMargaritaOcegueda

**What changed? Why?**
I´m changing the name of a function referred to in an explanation within the ERC20 token section.
'transfer' instead of '_mint'

2023-11-15 14:56 UTC, briandoyle81CB requested changes
Great catch, but can you please change it to `_transfer`?  

I'd do it, but then I lose the ability to approve.

2023-11-15 14:57 UTC, cb-heimdall commented
Review Error for briandoyle81CB @ 2023-11-15 14:57:32 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

2023-11-15 18:32 UTC, briandoyle81CB approved these changes

2023-11-15 18:32 UTC, briandoyle81CB approved these changes

2023-11-15 19:16 UTC, taycaldwell approved these changes

2023-11-15 19:24 UTC, briandoyle81CB approved these changes

2023-11-16 13:59 UTC, briandoyle81CB approved these changes

2023-11-16 15:59 UTC, taycaldwell approved these changes

2023-11-16 16:09 UTC, briandoyle81CB commented
@SilviaMargaritaOcegueda thanks and sorry for all the notifications about approvals.  One of our bots was misbehaving.

2023-11-16 16:09 UTC, merged