feat(ecosystem): Add plant-based to ecosystem.json
base-org/web pull request #1312
Opened 2024-11-28 15:18 UTC by aspiers

-------

**What changed? Why?**
Adds plantbased.art to the ecosystem page.

**Notes to reviewers**
plant-based was launched on Base as part of Onchain Summer 2024.

**How has it been tested?**
Ran yarn workspace @app/web dev on localhost.

2024-11-28 15:18 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-29 09:17 UTC, aspiers commented on apps/web/src/data/ecosystem.json
> +    "description": "plant-based is a (re)generative art series that evolves, grows and stores carbon. Created by cyrus clarke in partnership with Toucan and fxHash.",
He prefers lowercase - see the website.

2024-12-02 11:51 UTC, skripnike approved these changes

2024-12-02 11:51 UTC, cb-heimdall commented
Review Error for skripnike @ 2024-12-02 11:51:14 UTC
User must have write permissions to review

2024-12-07 10:21 UTC, wbnns approved these changes
ACK

@aspiers Thanks for building on Base 🔵

2024-12-07 10:22 UTC, wbnns requested changes
@aspiers 

Ah, it seems there is a merge conflict. Could you please resolve?

2024-12-07 10:40 UTC, aspiers commented
@wbnns Rebased and conflict resolved!

2024-12-22 14:42 UTC, aspiers commented
@wbnns Updated to new taxonomy.

2025-01-15 01:39 UTC, hughescoin approved these changes

2025-01-15 01:47 UTC, wbnns commented
@aspiers This can't be merged unless all of your commits are signed:
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2025-01-15 15:21 UTC, aspiers commented
Rebased, fixed author email, and GPG-signed.

2025-01-25 16:59 UTC, wbnns commented
@aspiers 

It looks like the commit wasn't signed, it is showing as `Unverified`:
https://github.com/base-org/web/pull/1312/commits

2025-02-05 00:52 UTC, wbnns commented
Adding in #1702

2025-02-05 00:52 UTC, closed without merging