revise ghostlogs to ghost with rebrand
base-org/web pull request #1327
Opened 2024-12-03 18:19 UTC by chrischang

**What changed? Why?**
Rebrand GhostLogs to Ghost

**Notes to reviewers**
Focus on the indexers (subgraphs) instead of gasless logs

**How has it been tested?**
Simple changes

2024-12-03 18:19 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-12-18 19:40 UTC, wbnns approved these changes

2024-12-18 19:41 UTC, wbnns requested changes
@chrischang 

Hello, could you please fix the merge conflict?

2024-12-18 19:49 UTC, chrischang commented
@wbnns done ✅ :)

2024-12-20 09:43 UTC, wbnns approved these changes
@chrischang Ty!

2024-12-21 10:17 UTC, wbnns commented
@chrischang Could you please rebase and sign your commits?

2024-12-21 17:14 UTC, chrischang commented
@wbnns rebased on pushed!

2025-01-15 01:38 UTC, hughescoin approved these changes

2025-01-15 01:42 UTC, ericbrown99 approved these changes

2025-01-15 01:48 UTC, wbnns commented
@chrischang This can't be merged unless all of your commits are signed:
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

You may need to do a full rebase

2025-01-15 01:51 UTC, chrischang commented
@wbnns will do

2025-01-15 02:01 UTC, chrischang commented
![Screenshot 2025-01-14 at 9 01 38 PM](https://github.com/user-attachments/assets/060ecd47-d2f0-42d4-ae7a-ef693455302b)

pushed the signed commit. thank you. @wbnns

2025-01-25 17:01 UTC, wbnns approved these changes

2025-01-25 17:01 UTC, merged