Fix typos
base-org/web pull request #1393
Opened 2024-12-14 18:50 UTC by VolodymyrBg

**What changed? Why?**
Fixed errors and inaccuracies in the project's textual materials. Improved readability of texts and documentation
**Notes to reviewers**
Regular text audits are recommended to maintain a high standard of quality
**How has it been tested?**
Changes have been reviewed to ensure no new errors were introduced

2024-12-14 18:50 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-12-18 13:18 UTC, wbnns requested changes
@VolodymyrBg 

Thanks for this PR! Left some comments in-line with changes we'd like to omit.

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/cookie-policy.mdx
> +purposes, such as to prevent unauthorized access attempts. You can set your browser to
Please omit this change

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/cookie-policy.mdx
> +When you access our Site and Services, we, or the companies we work with, may place cookies
Please omit this change

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/cookie-policy.mdx
> +and least popular and see how visitors move around the Site, and resolve any errors
Please omit this change

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/notices/decomissioning-public-geth-archive-snapshots.md
> +slug: /decommissioning-public-geth-archive-snapshots
Please omit this change

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/tools/basenames-onchainkit-tutorial.md
> +description: 'A tutorial that teaches how to integrate Basenames to your wagmi/viem App using OnchainKit'
Please omit this change

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/tools/basenames-onchainkit-tutorial.md
> +description: 'A tutorial that teaches how to integrate Basenames to your wagmi/viem App using OnchainKit'
(already fixed in a different PR)

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/notices/decomissioning-public-geth-archive-snapshots.md
> +slug: /decommissioning-public-geth-archive-snapshots
(already fixed in a different PR)

2024-12-18 13:18 UTC, wbnns commented on apps/base-docs/docs/tools/registry-faq.md
> +### How do I edit my entry if I make a mistake?
Please omit this change

2024-12-18 13:47 UTC, VolodymyrBg commented
@wbnns I don't know how to omit those changes correctly. I just edited those files and returned the version you wanted to see. Did I do it correctly?

2025-01-15 00:37 UTC, wbnns commented
@VolodymyrBg We're going to leave as-is for the time being. 🙏

2025-01-15 00:37 UTC, closed without merging