Adding project BlockAI/ BAI
base-org/web pull request #1487
Opened 2024-12-27 16:58 UTC by christopheSeeka

Adding BAI / BlockAI to ecosystem.json

2024-12-27 16:59 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-12-28 12:26 UTC, wbnns commented on apps/web/src/data/ecosystem.json
> +o[
This change should not be part of the PR

2024-12-28 12:27 UTC, wbnns requested changes
@christopheSeeka 

Hello, thanks for the new PR. There are two changes that would break the ecosystem page that seem to have been brought in with the code change. I've marked them in-line. There was also a small conjugation issue. Please fix. The rest of your PR LGTM. 👍

2024-12-28 12:28 UTC, wbnns commented on apps/web/src/data/ecosystem.json
> +    "description": "BlockAI combines blockchain and AI to offer decentralized access to innovative tools like Text and image generation, video summarization, games etc.",
Please add comma between games and etc.

2024-12-28 12:29 UTC, cb-heimdall commented
Review Error for wbnns @ 2024-12-28 12:29:00 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

2024-12-28 12:29 UTC, wbnns requested changes
Restarting Heimdall‎

2024-12-28 12:47 UTC, christopheSeeka commented
Updated, let me know if it's ok.

2024-12-30 11:50 UTC, wbnns commented
@christopheSeeka Hi, this still needs to be rebased. 🙏

2024-12-30 12:54 UTC, christopheSeeka commented
Ok will do, just to be sure is itmy rebase that arewrong or it isbecause thereisnew commitsin between approval time? 😇

2024-12-30 14:02 UTC, closed without merging