typo improvement
base-org/web pull request #1503
Opened 2024-12-29 13:47 UTC by prestoalvarez

Corrected `synpase` to `synapse`
Corrected `"Lyvely "` to `"Lyvely"`

2024-12-29 13:47 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-12-30 10:05 UTC, wbnns commented on apps/web/src/data/ecosystem.json
> +    "imageUrl": "/images/partners/synapse.webp",
The image file would also need to be updated to ensure there isn't a broken image

2024-12-30 10:05 UTC, wbnns requested changes
@prestoalvarez 

Thanks for this PR; left a comment in-line with a small change

2025-01-15 01:10 UTC, wbnns approved these changes
@prestoalvarez Thanks for contributing and for building on Base 🔵

2025-01-15 01:40 UTC, hughescoin approved these changes

2025-01-15 01:46 UTC, wbnns commented
@prestoalvarez This can't be merged unless all of your commits are signed

2025-01-25 17:19 UTC, wbnns commented
@prestoalvarez 

Thanks for the updates! Can you please also fix the typos in the `Lyvely` description?

2025-02-05 00:40 UTC, wbnns commented
Adding in #1702

2025-02-05 00:40 UTC, closed without merging