docs: Improve quickstart guide formatting and environment setup clarity
base-org/web pull request #1508
Opened 2024-12-30 02:16 UTC by DeVikingMark

## This PR enhances the Base quickstart guide with several improvements:

- Remove quotes from environment variables in .env example for better consistency with common practices
- Add warning message about requiring test ETH before contract deployment to prevent failed transactions
- Clean up excessive line breaks at the end of the document
- Improve readability by adding proper spacing after the foundryup command

### These changes make the documentation more user-friendly and align with standard documentation practices.

## Changes made:
1. Simplified .env variables format
2. Added explicit warning about test ETH requirements
3. Reduced redundant <br/> tags
4. Fixed spacing inconsistencies

## Testing:
- Verified all markdown formatting renders correctly
- Confirmed all links are working
- Checked that code examples are properly formatted

2024-12-30 02:16 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-12-30 10:12 UTC, wbnns commented on apps/base-docs/docs/building-with-base/quickstart.md
> +BASE_RPC_URL=https://mainnet.base.org
Please drop this change; we prefer to use quotes in this context

2024-12-30 10:12 UTC, wbnns requested changes
@DeVikingMark 

Thanks for this PR! Left a nit in-line.

2025-01-15 01:08 UTC, wbnns commented on apps/base-docs/docs/building-with-base/quickstart.md
> +:::
Please include a line break before this line

2025-01-15 01:09 UTC, wbnns commented
@DeVikingMark Thanks for the updates! Left two more small nits inline and then this should be good to come in!

2025-01-25 17:28 UTC, wbnns approved these changes

2025-01-25 17:28 UTC, cb-heimdall commented
Review Error for wbnns @ 2025-01-25 17:28:21 UTC
User cannot review their own commit

2025-01-26 20:07 UTC, brendan-defi approved these changes

2025-01-26 20:18 UTC, merged