Add Scopescan.ai to the explorer doc section
base-org/web pull request #226
Opened 2024-01-02 16:22 UTC by RedHorse823

**What changed? Why?**

I add Scopescan, a data analytic platform (similar to Arkham & Nansen) to the block explorer documentation page.

This is because since we have Arkham on this page, Scopescan also support to check Base transactions & tokens & addresses, they also have other nice features like:

1. moneyflow tool to visualize token flows
2. Token holder graph to visualize token holder distributions
3. Smartmoney dashboard to check who made the most money on Base

**Notes to reviewers**

Scopescan is power by 0xscope, they received legit fundings from OKX and Hashkey.

I believe Scopescan can help a lot with Base users with their data and tooling ability. That's why i propose this change. Hope it get approved, thanks!

Scopescan.ai is their platform link, you can try and decide.

2024-01-03 01:23 UTC, wbnns commented
@RedHorse823 

Thanks for taking the time to open this PR! We've added this to our backlog, pending to be reviewed.

2024-02-29 06:00 UTC, RedHorse823 commented
Hi Team is this repo okay to be merged? Just asking, thanks! @cb-heimdall

2024-05-23 16:46 UTC, wbnns requested changes
@RedHorse823 

Hi there! Thanks for this contribution! Can you please update this PR to list Scopescan alphanumerically in order with the others in the list?

2024-05-23 16:46 UTC, wbnns commented on apps/base-docs/docs/tools/block-explorers.md
> +Scopescan supports [Platform](https://scopescan.ai/home?network=base) Base on their platform.
Please update link to new domain

2024-05-23 16:47 UTC, wbnns commented on apps/base-docs/docs/tools/block-explorers.md
> +Base voyagers can check Base transaction records, addresses, tokens, and even smart moneys on their platforms.
s/and even smart moneys/and other traits/

s/platforms/platform/

2024-05-23 16:48 UTC, wbnns commented on apps/base-docs/docs/tools/block-explorers.md
> +Scopescan is an on-chain data analytics platform that greatly enhances the on-chain analytical experience."
s/on-chain/onchain/

Please remove `"` at the end of the sentence.

2024-06-06 01:04 UTC, wbnns commented
@RedHorse823 

Heya, since it has been some time and we haven't heard back, I'm going to go ahead and close this PR for now. If you'd like to pursue these changes in the future please let us know and we can reopen. 👍

2024-06-06 01:04 UTC, closed without merging