Add advanced frames guide
base-org/web pull request #322
Opened 2024-02-09 22:26 UTC by briandoyle81CB

**What changed? Why?**
Add advanced frames guide

**Notes to reviewers**

**How has it been tested?**

**Does this PR add a new token to the bridge?**

- [ ] No, this PR does not add a new token to the bridge
- [ ] I've confirmed this token doesn't use a bridge override
- [ ] I've confirmed this token is an OptimismMintableERC20

Please include evidence of both confirmations above for your reviewers.

2024-02-09 22:35 UTC, taycaldwell requested changes

2024-02-09 22:35 UTC, taycaldwell commented on apps/base-docs/docs/building-with-base/guides/advanced-frame-behavior.md
> +    frames
add a comma at the end of this line

2024-02-09 22:35 UTC, taycaldwell commented on apps/base-docs/docs/building-with-base/guides/advanced-frame-behavior.md
> +As [Frames] on [Farcaster] grow in popularity, developers are building more complex interactions to meet the community's expectation for new and exciting things to do. [OnchainKit], and our [a-frame-
`withing` -> `within`

2024-02-09 22:35 UTC, taycaldwell commented on apps/base-docs/docs/building-with-base/guides/advanced-frame-behavior.md
> +You can now add outbound links to buttons. To do this, with [OnchainKit], simply create a button with an `action` property of `link`, and a `target` of the desired url:
remove the comma after `To do this`

2024-02-10 01:19 UTC, wbnns approved these changes

2024-02-10 01:19 UTC, merged