[DO NOT MERGE] Add Wallet Connector to Navbar (WIP)
base-org/web pull request #423
Opened 2024-04-09 12:36 UTC by taycaldwell

**What changed? Why?**
- Add wallet connector (RainbowKit) to docs navbar

**Notes to reviewers**
Work in progress. Do not merge.

**How has it been tested?**
Manually

**Does this PR add a new token to the bridge?**

Are you adding an entry to [`assets.ts`](../apps/bridge/assets.ts)?

- [x] No, this PR does not add a new token to the bridge
- [ ] Yes, and I've confirmed this token doesn't use a bridge override
- [ ] Yes, and I've confirmed this token is an OptimismMintableERC20

If you are adding a token to the bridge, please include evidence of both confirmations above for your reviewers.

2024-04-12 21:53 UTC, briandoyle81CB requested changes
Looks great but is breaking Cafe:  http://localhost:3000/base-camp/docs/storage/storage-exercise

It's breaking because it's using wagmi 1.x and needs to be updated.

I also worry about having Base mainnet as a network.  It's going to create the risk of someone spending a lot of real ETH to do one of the exercises.  

If we need mainnet on the site, we should make sure there are safeguards.

2024-04-12 21:54 UTC, cb-heimdall commented
Review Error for briandoyle81CB @ 2024-04-12 21:54:22 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

2024-04-16 20:36 UTC, zencephalon commented on apps/base-docs/src/theme/NavbarItem/styles.module.css
> +  background-color: rgb(235, 237, 240) !important;
Should we name these colors somehow?

2024-04-16 20:37 UTC, zencephalon commented on apps/base-docs/src/theme/NavbarItem/ComponentTypes.js
> +                      {account.ensName ? account.ensName : account.displayName}
Maybe just `account.ensName ?? account.displayName`

2024-04-16 20:38 UTC, zencephalon commented on apps/base-docs/src/theme/Navbar/MobileSidebar/Header/index.js
> +      onClick={() => mobileSidebar.toggle()}
Nit, `useCallback`

2024-04-16 21:00 UTC, wbnns submitted a review, later dismissed
When canceling the request to connect my wallet, I get an uncaught exception:

![2024-04-16 at 20 55 37@2x](https://github.com/base-org/web/assets/1130872/c48bb360-9a32-43df-901b-dcfd0593dfb9)

Tested w/ Coinbase Wallet, MetaMask and Brave on desktop.

@taycaldwell Will mobile users who have a mobile wallet installed be able to connect?

2024-04-16 21:04 UTC, taycaldwell commented
Need to gracefully handle these wallet errors across the site. Looking into how to do that with wagmi v2 / viem, because it was happening for Base Camp stuff too.

2024-04-20 11:29 UTC, wbnns commented
@taycaldwell

Thanks for the updates! Looks like there is a merge conflict in `apps/base-docs/tutorials/data.json`

2024-04-20 20:00 UTC, briandoyle81CB approved these changes

2024-04-22 12:57 UTC, merged