Update Frontend Content to use Wagmi v2
base-org/web pull request #446
Opened 2024-04-17 20:54 UTC by briandoyle81CB

**What changed? Why?**
Wagmi v2 is very breaking.  Updated tutorials to new methods.

**Notes to reviewers**

**How has it been tested?**

**Does this PR add a new token to the bridge?**

Are you adding an entry to [`assets.ts`](../apps/bridge/assets.ts)?

- [ ] No, this PR does not add a new token to the bridge
- [ ] Yes, and I've confirmed this token doesn't use a bridge override
- [ ] Yes, and I've confirmed this token is an OptimismMintableERC20

If you are adding a token to the bridge, please include evidence of both confirmations above for your reviewers.

2024-04-17 22:36 UTC, taycaldwell commented on apps/base-docs/base-camp/docs/frontend-setup/building-an-onchain-app.md
> +As discussed above, add ``"use client":` to the top of the file.
Extra ` I think on this line?

2024-04-17 22:38 UTC, taycaldwell commented on apps/base-docs/base-camp/docs/reading-and-displaying-data/configuring-useReadContract.md
> +  projectId: '51407fcf066d74968d9a1a4c6da0d994',
Should this be a placeholder string?

2024-04-17 22:40 UTC, taycaldwell commented on apps/base-docs/base-camp/docs/reading-and-displaying-data/useAccount.md
> +    {!isConnected && <p>Please click Connect in your wallet...</p>}
`isConnecting` is still exists in v2.

2024-04-17 22:42 UTC, taycaldwell requested changes
Minor comments. Otherwise LGTM.

2024-04-18 12:03 UTC, briandoyle81CB commented on apps/base-docs/base-camp/docs/reading-and-displaying-data/configuring-useReadContract.md
> +  projectId: '51407fcf066d74968d9a1a4c6da0d994',
Haha whoops

2024-04-19 14:13 UTC, merged