Master
base-org/web pull request #522
Opened 2024-05-30 02:45 UTC by agol586

**What changed? Why?**
    Add RockX to node providers

**Notes to reviewers**
  N/A

**How has it been tested?**
  Manually

2024-06-03 20:14 UTC, wbnns commented on apps/base-docs/docs/tools/node-providers.md
> +[RockX](https://access.rockx.com) offers a global blockchain node network and developer tools for Web3 innovation. Start with our free [Base RPC] (https://access.rockx.com/product/base-blockchain-api
@agol586 

There's a missing space that's breaking the hyperlink for `Base RPC` could you please fix?

2024-06-03 20:14 UTC, wbnns requested changes
Small nit WRT link.

2024-06-06 01:14 UTC, wbnns approved these changes

2024-06-06 13:10 UTC, briandoyle81CB commented on apps/base-docs/docs/tools/node-providers.md
> +[RockX](https://access.rockx.com) offers a global blockchain node network and developer tools for Web3 innovation. Start with our free [Base RPC](https://access.rockx.com/product/base-blockchain-api-
Can we please say "onchain" instead of "Web3"?

2024-06-06 13:10 UTC, briandoyle81CB requested changes
Can we please say "onchain" instead of "Web3"?

2024-06-06 13:11 UTC, cb-heimdall commented
Review Error for briandoyle81CB @ 2024-06-06 13:11:42 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

2024-06-09 00:01 UTC, zencephalon approved these changes

2024-06-10 13:06 UTC, briandoyle81CB approved these changes

2024-06-10 13:06 UTC, merged