New guide (tutorial): Build a Dynamic NFT on Base with Irys
base-org/web pull request #523
Opened 2024-05-30 15:07 UTC by lukecd

**What changed? Why?**
- This PR adds a new guide teaching users how to use Irys to create a dynamic NFT. 
- The guide can be accessed at `/tutorials/dynaimc-nfts`

**Notes to reviewers**
- This PR started with a conversation I had with Gavynn Arteaga about adding an Irys-related guide to the Base docs

**How has it been tested?**
- The code has been tested multiple times
- The writing style matches the [Base style guide](https://github.com/base-org/web/wiki/Style-Guide-for-Tutorials)
- The graphics use Base fonts and colors from the Base brand kit

2024-06-03 15:32 UTC, briandoyle81CB requested changes
Please change to reference-style links (https://www.markdownguide.org/basic-syntax/) and add a conclusion paragraph that restates the learning objectives.

Looks great otherwise, will approve after the above.  Thanks for adding this!

2024-06-04 11:56 UTC, lukecd commented
Thanks for the review. I pushed a new version with a conclusion and reference style links. All should be good to go now.

Happy  OᑎᑕᕼᗩIᑎ ᔑᑌᗰᗰEᖇ! :)

2024-06-10 15:11 UTC, briandoyle81CB approved these changes
@lukecd thanks for being so patient with all the nits.  Great article!

2024-06-10 15:13 UTC, briandoyle81CB approved these changes

2024-06-10 15:16 UTC, zencephalon approved these changes

2024-06-10 15:17 UTC, merged