Update node-providers.md
base-org/web pull request #525
Opened 2024-05-31 04:50 UTC by yunseonna

Proposing to update additional possible free RPC endpoint powered by All That Node.

**What changed? Why?**

**Notes to reviewers**

**How has it been tested?**

2024-06-03 20:23 UTC, wbnns requested changes
@yunseonna 

Hi there! Looks like the link for All That Node goes to a page about zkSync -- is there a Base-specific landing page you can update the link to? Otherwise, this would be confusing to Base users.

2024-06-04 05:50 UTC, yunseonna commented
Oh sorry, I've changed the link!

2024-06-06 01:22 UTC, wbnns commented on apps/base-docs/docs/tools/node-providers.md
> +[All That Node](https://www.allthatnode.com/base.dsrv) is the most comprehensive multi-chain development suite, designed to support multiple networks from a single platform. They offer free and [paid
@yunseonna 

Could you also please update to remove the superlative?

s/is the most/is a/

2024-06-06 01:23 UTC, wbnns requested changes
Left a small nit in-line.

2024-06-10 11:55 UTC, yunseonna commented
I've chenaged it! Thanks in advance.

2024-06-17 14:41 UTC, wbnns approved these changes
ACK

@yunseonna Thanks for the updates and for building on Base 🔵

2024-06-17 14:47 UTC, merged