Update: API3 under Oracles section
base-org/web pull request #575
Opened 2024-06-19 07:31 UTC by vanshwassan

Updated content for API3 dev docs under `base-docs/docs/tools/oracles.md`

2024-06-24 14:04 UTC, wbnns requested changes
@vanshwassan 

Thanks for this PR! Just left a few nits in-line.

2024-06-24 14:04 UTC, wbnns commented on apps/base-docs/docs/tools/oracles.md
> +Apart from data feeds, API3 also provides [Quantum Random Number Generation](https://docs.api3.org/explore/qrng/) on Base Mainnet and Testnet. QRNG is a free-to-use service that provides quantum rand
s/on-chain/onchain/

2024-06-24 14:04 UTC, wbnns commented on apps/base-docs/docs/tools/oracles.md
> +The API3 Market provides access to 200+ price feeds on [Base Mainnet](https://market.api3.org/base) and [Testnet](https://market.api3.org/base-sepolia-testnet). The price feeds operate as a native pu
s/Testnet/Base Testnet/

2024-09-20 13:40 UTC, zencephalon approved these changes

2024-09-20 13:40 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>1/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-10-18 07:02 UTC, wbnns approved these changes
ACK

@vanshwassan Thanks!

2024-10-18 16:02 UTC, brendan-defi commented
@wbnns @vanshwassan could y'all clear up the merge conflicts please? i'll take a look once resolved

2024-10-18 21:31 UTC, wbnns commented
> @wbnns @vanshwassan could y'all clear up the merge conflicts please? i'll take a look once resolved

@brendan-defi Updated, thanks 🤝

2024-10-18 21:41 UTC, brendan-defi approved these changes

2024-10-18 21:42 UTC, merged