docs: update "run a base node" instructions
base-org/web pull request #80
Opened 2023-10-23 19:05 UTC by boldkoala4615

**What changed? Why?**
instructions seem outdated. `OP_NODE_L1_ETH_RPC` is no longer configurable in `docker-compose.yml`

**Notes to reviewers**
none

**How has it been tested?**
compiled the md file

2023-10-24 01:04 UTC, zencephalon commented
@boldkoala4615 Thank U for fixing this!

2023-10-24 10:40 UTC, wbnns requested changes
@boldkoala4615 

Heya! Nice catch! Can you please update the line to match the instructions that are in the Base Node repostiory? https://github.com/base-org/node#usage

![2023-10-24 at 10 40 24@2x](https://github.com/base-org/web/assets/1130872/6beabc73-112b-4867-90c6-69b7be6b357b)

2023-10-24 10:41 UTC, cb-heimdall commented
Review Error for wbnns @ 2023-10-24 10:41:39 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

2023-10-24 12:36 UTC, boldkoala4615 commented
Thanks for the feedback, ready for another 👀

2023-10-24 12:37 UTC, boldkoala4615 commented
Setting the `OP_NODE_L1_ETH_RPC` is optional, right? The wording kind of implies it's a mandatory step, but it works perfectly fine without setting one. I'm assuming this is only required when one wants to customize the ETH RPC. Happy to adapt the wording if warranted.

2023-10-24 14:03 UTC, zencephalon commented
@boldkoala4615 I believe U've got the right interpretation, yes

2023-10-24 21:21 UTC, zencephalon approved these changes

2023-10-24 21:22 UTC, merged

2023-10-26 14:17 UTC, boldkoala4615 commented
Thanks for the support @zencephalon

2023-10-26 15:02 UTC, zencephalon commented
@boldkoala4615 thanks again for your contribution!