docs: erpc
base-org/web pull request #804
Opened 2024-08-08 13:29 UTC by kasrakhosravi

**What changed? Why?**

Adding [eRPC](https://github.com/erpc/erpc) to Base docs.

![Screenshot 2024-11-07 at 10 29 14](https://github.com/user-attachments/assets/fa0884d1-9c81-49ee-b339-6cec028fcde2)

**Notes to reviewers**

**How has it been tested?**

2024-08-08 13:29 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-02 05:35 UTC, wbnns requested changes
@kasrakhosravi 

Thanks for this PR. Apologies, we'd need multiple options before we can create an additional page. Would eRPC fit within the current Node Providers page?

2024-12-13 20:44 UTC, wbnns commented on apps/base-docs/docs/tools/node-providers.md
> +To get started, visit the [develoepr documentation](https://docs.erpc.cloud/).
s/develoepr/developer/

2024-12-13 20:45 UTC, wbnns commented
@kasrakhosravi 

Could you please fix the typo in the latest update?

2024-12-18 19:16 UTC, closed without merging