Add 'Verify Smart Contracts with Basescan API' tutorial
base-org/web pull request #853
Opened 2024-08-15 20:34 UTC by hughescoin

**What changed? Why?**
New tutorial with images
**Notes to reviewers**

**How has it been tested?**

2024-08-16 00:35 UTC, briandoyle81CB commented on apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
> +Solidity is the primary programming language for writing smart contracts on Ethereum and Ethereum-compatible blockchains like Base. You should be comfortable with writing, compiling, and deploying ba
Can you please link to base.org/learn here?

2024-08-16 00:35 UTC, briandoyle81CB commented on apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
> +Foundry is a fast and portable toolkit for Ethereum application development. It simplifies the process of deploying, testing, and interacting with smart contracts. This tutorial assumes you have expe
Link to intro to Foundry tutorial

2024-08-16 00:36 UTC, briandoyle81CB commented on apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
> +For this turotial, we will deploy a simple contract that is included in the Foundry quickstart. To do so, ensure that you have Foundry installed.
Please change 'we' to you

2024-08-16 00:36 UTC, briandoyle81CB commented on apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
> +You (the deployer wallet) will need some ETH in order to broadcast the transaction to the Base network. Fortunately, transactions are usually < 1 cent on Base mainnet.
I'm 85% sure the admonishments need an empty line after the opening ::: and before the closing :::

2024-08-16 00:37 UTC, briandoyle81CB commented on apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
> +export PRIVATE_KEY="f980byuhjhgfr45tyhglQxydfG5yu765rf"
I'd replace this with <your key here> 

Otherwise, I worry about someone accidentally doing something important with an exposed key.

2024-08-16 00:40 UTC, briandoyle81CB commented on apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
> +    contractaddress: '0x8aB096ea9886ACe363f81068d2439033F67F62E4',
I'd put <Your contract address>

2024-08-16 00:41 UTC, briandoyle81CB commented on apps/base-docs/tutorials/docs/1_verify-contract-with-basescan.md
> +If successful, your terminal should output JSON text with three properties `status`, `message` and `result` like below:
Consider using "will" instead of "should" throughout the article

2024-08-16 00:42 UTC, briandoyle81CB requested changes
Great tutorial!  A few minor items in content

2024-08-20 01:34 UTC, zencephalon approved these changes

2024-08-20 01:48 UTC, merged