Add Quickstart Guide to docs.base.org/docs
base-org/web pull request #998
Opened 2024-09-12 18:41 UTC by ericbrown99

**What changed? Why?**
Added a Quickstart: Deploy on Base guide to the `Building on Base` section of the docs. 

The intention of this guide is to stay as high level as possible while still providing enough information for new developers to deploy contracts to Base. It uses the Foundry framework to support this process. 

**Notes to reviewers**
Please review for correctness and consistency of language. Please follow the tutorial and ensure you are able to replicate the results by exactly following the steps outlined in the guide to ensure everyone will have success. 

**How has it been tested?**
I tested this by spinning up a fresh directory and following the steps exactly to ensure I was able to deploy and interact with contracts from my local machine.

2024-09-12 18:41 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/2</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-09-13 17:07 UTC, ericbrown99 commented
cc @wbnns & @hughescoin

2024-09-14 08:41 UTC, wbnns requested changes
@ericm-cb 

Heya! Thanks for putting this together! Left two comments in-line w/ small nits but otherwise LGTM! Can you please merge in the latest changes from `master`?

Also, a question -- I noticed what looked like maybe a couple of artifacts in these commit titles:
c5fdd91a1212fb42616f616deb46315ce6bde2b3
3f48d4c2fbd8d870f9ef32ee01c330aefdc4be9d

 I didn't see any translations in this PR. PLMK if I should be looking somewhere else for the correlation here. 👍

2024-09-14 08:41 UTC, wbnns commented on apps/base-docs/docs/building-with-base/quickstart.md
> +- Set up your develompent environment to deploy on Base
s/develompent/development/

2024-09-14 08:41 UTC, wbnns commented on apps/base-docs/docs/building-with-base/quickstart.md
> +Now that your enviornment is set up, let's deploy your contracts to Base Sepolia.
s/enviornment/environment/

2024-09-26 13:24 UTC, ericbrown99 commented
> Also, a question -- I noticed what looked like maybe a couple of artifacts in these commit titles: [c5fdd91](https://github.com/base-org/web/commit/c5fdd91a1212fb42616f616deb46315ce6bde2b3) [3f48d4c](https://github.com/base-org/web/commit/3f48d4c2fbd8d870f9ef32ee01c330aefdc4be9d)
> 
> I didn't see any translations in this PR. PLMK if I should be looking somewhere else for the correlation here. 👍

Good catch, fixed the artifacts 👍

2024-09-26 13:28 UTC, ericbrown99 commented
@wbnns & @hughescoin 

Fixed the open items above and merged in the latest from master, thanks! Mind taking a last quick look and then LGTM 🚀

2024-09-26 20:20 UTC, wbnns requested changes
@ericbrown99 

Heya, looks like there is an artifact in `yarn.lock` which is causing the build to fail

2024-09-26 20:21 UTC, cb-heimdall commented
Review Error for wbnns @ 2024-09-26 20:21:58 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

2024-09-26 21:30 UTC, hughescoin approved these changes

2024-09-26 21:31 UTC, cb-heimdall commented
Review Error for hughescoin @ 2024-09-26 21:31:46 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

2024-09-27 03:39 UTC, hughescoin approved these changes

2024-09-27 03:58 UTC, merged